### PR TITLE
Merge all the changes from joelmoss' fork

### PR DESCRIPTION
**Pull request by mathieujobin**
@joelmoss used to maintain this gem.
Not anymore.

Would it make sense to move all the commits to the original repo?

### CODE REVIEW

**Comment by sikachu** [comment]
Thank you for the PR.

I think the original idea of having the repository on @joelmoss account instead because Rails team decided to no longer maintaining this gem. However, I think that was before GitHub actually have an archive feature, so we just left this repository open like this?

If you (or someone else) would like to step up as a maintainer, I think it's ok for them to fork the project and ask Rails Core team to link to the maintained fork instead.

@rafaelfranca should we archive this repository once we find a new maintainer, or what do you think how we should handle this situation?

**Comment by joelmoss** [comment]
Sorry guys, but I no longer use or maintain this gem. And was also surprised to find that it is still used. I think there are better solutions.

I have archived my fork and am happy for anyone to do what they want with it.

**Comment by mathieujobin** [comment]
@joelmoss can you pass me the rubygems push rights? If I can get an update for Rails 7, I will push it.

**Comment by mathieujobin** [comment]
@joelmoss it would be useful if you had not archived your repos, so discussions on open PR could be continued without being moved unnecessarily.

this commit https://github.com/joelmoss/dynamic_form/commit/20fa1f3c398968b46d2114eae3316ba514b5d227 has to be reverted, as the doc isn't updated and it is a breaking change.

**Comment by mathieujobin** [comment]
@janxious  @calebwoods  @Narnach  @robmathews 

FYI ! I will be pushing my stuff to https://github.com/payrollhero/dynamic_form

basically, I am using @robmathews  open PR branch with that commit above reverted 20fa1f3

**Comment by mathieujobin** [comment]
@joelmoss Sorry to be bothering you with this again, but If I could get push rights to https://rubygems.org/gems/dynamic_form 

I could publish an updated version with Rails 7 support.

I maintain many old legacy gems, see my profile https://rubygems.org/profiles/mathieu

Thanks

**Comment by joelmoss** [comment]
Done! its all yours

**Comment by mathieujobin** [comment]
Thank you

**Comment by mathieujobin** [comment]
v1.2.0 released https://rubygems.org/gems/dynamic_form

source live at https://github.com/payrollhero/dynamic_form for now

**Pull request closed without merging**
